DROP TABLE IF EXISTS 환자;
DROP TABLE IF EXISTS 병원;
DROP TABLE IF EXISTS 접수;
CREATE TABLE IF NOT EXISTS "병원" (
	"병원ID"		INTEGER NOT NULL,
	"병원이름"		TEXT,
	"입원환자"		INTEGER,
	"최대입원환자"	INTEGER,
	"전화번호"		INTEGER,
	PRIMARY KEY("병원ID")
);
CREATE TABLE IF NOT EXISTS "환자" (
	"연번"		INTEGER,
	"확진일"	INTEGER,
	"지역"		TEXT,
	"여행력"	TEXT,
	"접촉력"	TEXT,
	PRIMARY KEY("연번")
);
CREATE TABLE IF NOT EXISTS "접수" (
	"연번"		INTEGER NOT NULL,	
	"병원ID"	INTEGER,
	"상태"		TEXT,
	FOREIGN KEY("병원ID") REFERENCES "병원"("병원ID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("연번") REFERENCES "환자"("연번") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("연번")
);
